---
- hosts: localhost
  connection: local
  become: true
  vars:
    users:
      - jmanzur
      - root
  pre_tasks:
  - name: Update and Upgrade
    apt:
      update_cache: yes
      upgrade: 'yes'

  tasks:
  - name: Install packages
    package:
      name:
        - gnupg
        - software-properties-common
        - htop
        - vim
        - curl
        - net-tools
        - sshpass
        - dos2unix
        - telnet
        - whois
        - tree
        - neofetch
        - git
        - ansible
        - jq
        - pass
        - gnupg2
        - silversearcher-ag
        - zsh
        - npm
        - unzip
        - bat
        - openssl

  - name: Check if AWS CLI is installed
    ansible.builtin.command: aws --version
    register: awscli_check
    ignore_errors: yes

  - name: Install AWS CLI
    ansible.builtin.shell: |
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install
    when: awscli_check.rc != 0
    
  - name: Install Fuzzy Finder
    ansible.builtin.shell: |
      git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
      ~/.fzf/install

  - name: Install kubectl
    ansible.builtin.shell: |
      curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      chmod +x kubectl
      sudo mv kubectl /usr/local/bin/

  - name: Install Helm
    ansible.builtin.shell: |
      curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
      chmod 700 get_helm.sh
      ./get_helm.sh && rm get_helm.sh

  - name: Install ArgoCD CLI
    ansible.builtin.shell: |
      curl -sSL -o argocd-linux-amd64 https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
      sudo install -m 555 argocd-linux-amd64 /usr/local/bin/argocd && rm argocd-linux-amd64
  
  - name: Install Terraform
    ansible.builtin.shell: |
      sudo apt-get update && sudo apt-get install -y gnupg software-properties-common
      wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg > /dev/null
      gpg --no-default-keyring --keyring /usr/share/keyrings/hashicorp-archive-keyring.gpg --fingerprint
      echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
      sudo apt-get update && sudo apt-get install terraform

  - name: Install Go
    ansible.builtin.shell: |
      GO_TAR="go1.23.0.linux-amd64.tar.gz"
      sudo wget -qcO /usr/local/$GO_TAR https://go.dev/dl/$GO_TAR
      sudo tar -C /usr/local -xzf /usr/local/$GO_TAR
      sudo rm -rf /usr/local/$GO_TAR
      export PATH=$PATH:/usr/local/go/bin

  - name: Install eks-node-viewer
    ansible.builtin.shell: |
      go install github.com/awslabs/eks-node-viewer/cmd/eks-node-viewer@latest


