---
- hosts: localhost
  connection: local
  become: true
  pre_tasks:
  - name: Update and Upgrade
    apt:
      update_cache: yes
      upgrade: 'yes'

  tasks:
  - name: Install packages
    package:
      name:
        - htop
        - vim
        - curl
        - zsh
        - net-tools
        
  - name: Download zsh installer
    get_url:
      url: https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh
      dest: ./zsh-installer.sh

  - name: Execute the zsh-installer.sh
    shell: ./zsh-installer.sh

  - name: Remove the zsh-installer.sh
    file:
      path: ./zsh-installer.sh 
      state: absent