---
- hosts: localhost
  connection: local
  become: true
  pre_tasks:
  - name: Update and Upgrade
    apt:
      update_cache: yes
      upgrade: 'yes'

  tasks:
  - name: Install packages
    package:
      name:
        - htop
        - vim
        - curl
        - zsh
        - net-tools

  - name: Install Oh-My-ZSH
    command: sh -c "$(wget https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh -O -)"