---
- hosts: localhost
  connection: local
  become: true
  pre_tasks:
  - name: Update and Upgrade
    apt:
      update_cache: yes
      upgrade: 'yes'

  tasks:
  - name: Install packages
    package:
      name:
        - gnupg
        - software-properties-common
        - htop
        - vim
        - curl
        - net-tools
        - sshpass
        - dos2unix
        - telnet
        - whois
        - tree
        - neofetch
        - git
        - ansible
        - jq
        - pass
        - gnupg2
        - silversearcher-ag

  - name: Install Oh-My-Bash
    shell: |
      bash -c "$(curl -fsSL https://raw.githubusercontent.com/ohmybash/oh-my-bash/master/tools/install.sh)" --unattended