---
- hosts: localhost
  connection: local
  become: true
  pre_tasks:
  - name: Update and Upgrade
    apt:
      update_cache: yes
      upgrade: 'yes'

  tasks:
  - name: Install packages
    package:
      name:
        - gnupg
        - software-properties-common
        - htop
        - vim
        - curl
        - net-tools
        - sshpass
        - dos2unix
        - telnet
        - whois
        - tree
        - neofetch
        - git
        - ansible
        - jq
        - pass
        - gnupg2
        - silversearcher-ag

  - name: Check if Oh My Bash is installed
    stat:
      path: "~/.oh-my-bash"
    register: oh_my_bash

  - name: Install Oh My Bash for all users
    hosts: all
    vars:
      users:
        - jmanzur
        - root
    tasks:
      - name: Install Oh My Bash for each user
        become: yes
        become_user: "{{ item }}"
        shell: bash -c "$(curl -fsSL https://raw.githubusercontent.com/ohmybash/oh-my-bash/master/tools/install.sh)" --unattended
        loop: "{{ users }}"
        when: not oh_my_bash.stat.exists